---
title: "Assignments"
slug: assignments
---

# Attendance & Participation

You are expected to attend class and actively participate (e.g., ask questions, provide your perspective). 

You are permitted to miss to have two (2) unexcused absences. Excused absences must be approved before the class and can only be approved for medical issues (with a doctor's note) or work-travel related.

Attendance will be **taken during break on a written sheet of paper**. Each unexcused absences after your first two unexcused absences will decrease your Attendance grade by **10%**.

For example, if you have four unexcused absences and perfect participation, your Attendance grade will be 80% as first two unexcused absences will not have an effect.

# DataCamp Courses

<span class="newthought">To reinforce programming concepts, </span> you will need to complete **four** DataCamp courses. Credit will either be granted for completion on time or no credit. These will be assigned on DataCamp and are intended to reinforce the programming assignments and material. 

**No partial credit (only complete X chapters) will be granted.** You either completed the course or not.

**50%** penalty 1 day late. Longer than 1 day will receive 0% credit. 

All four DataCamp courses are available at the beginning of the course. Therefore, you can begin DataCamp courses before we cover the related material.

# Problem sets

<span class="newthought">To practice working with R/RStudio</span> and making data-based graphics, you will complete a series of 4 problem sets. You need to show that you made a good faith effort to work each question. The problem sets will also be graded on the following point system:

- Can your results be replicated? e.g., files run, includes .Rmd/.html files + data/images
- Your explanations of the code written in grammatically correct English 
- The correctness of your code

You may (and should!) work with one other person on the problem sets, but you **must** turn in your own answers. You cannot work in groups of more than **two** people, and you must note who you worked with on your assignment.

**50%** penalty 1 day late. Longer than 1 day will receive 0% credit. 

# Quizzes

<span class="newthought">Quizzes</span> are intended to reinforce the lectures and course reading materials. Quizzes will be given out-of-class through Canvas. Each quiz will consist of ten (10) multiple choice questions for each quiz. Quizzes will be closed-book, i.e., you **cannot use any other resource** (no phones, laptops, books, etc.).

I will try to review each quiz in the following class to provide feedback on each quiz. Your grades will be posted on Canvas.

**No late submissions**. After the deadline, if you did not complete your quiz, you will receive a 0% grade. 

# Extra Credit

You may receive up to **5%** extra credit to be added to your final grade. This is equivalent to a problem set or quiz grade (e.g., if you missed one). Extra points on problem sets or projects do not count towards this cap and are separate.

Once a student hits the 5% cap, any additional work will not count towards extra credit.

Other opportunities may arise through the semester but I'll make an annoucement as they become official.

```{r assignments-grades, echo=F}
assignments <- tibble::tribble(
  ~Task,  ~Instructions, ~Points,
  "Create your own\nblogdown website." , "See link below.", "2%",
  "Attend R Meetup Group (Sept, Oct, Nov)", "See link below.", "1%",
  "Slack participation*" , "Answer a question or provide an interesting post/finding. You'll only get credit if I respond #slackextracredit.", "0.25%"
) 

knitr::kable(assignments)
```

- [Create your own blogdown website](../../assignment/01-extra-credit/)
- [Charlotte R Meetup Group](https://www.meetup.com/Charlotte-R-Users-Group/)

*For Slack, you can only have up to 8 times (so 2% total extra points).

To get extra credit, please DM me on Slack (e.g., for blogdown, you need to provide your netlify website.)

# Design Contest / Mini-Project

<span class="newthought">To give you practice for the final project</span>, you will complete a mini-project halfway through the semester. I will provide you with real-world data and pose one or more questions—you will make a static visualization plots.

The goal of this project is to give you practice to design visualization solution for an interesting data problem. You are **not** expected to use Shiny since we will not have covered that material in detail. Instead, you need to outline what skills/tools you want to learn more to better for the final project (e.g., what would you want to do if you could).

Feel free to start thinking about ideas (datasets, research questions) now. This will be in groups of no more than 3 students per group.

This project is worth **10%** of your final course grade. You will have an in-class, 10 minute presentation on **October 28th** and submit your materials in Canvas.

# Final project

<span class="newthought">At the end of the course,</span> you will demonstrate your data visualization skills by completing a final project.

Project details will be posted later on. This much is certain so far:

- You will use some sort of real-world, interactive data visualization (Shiny-based) some sort of research question.
- The project will consist of a written report and a final 10 minute presentation, which will be during our Exam class on December 9th.

There is no final exam. This project is your final exam.
