---
title: "Introduction to Visual Analytics"
date: "2019-08-19"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

# Tweet of the day:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Any time I have been struggling to learn a new tool/technology/software ... I go back to this short clip I cut out of <a href="https://twitter.com/hadleywickham?ref_src=twsrc%5Etfw">@hadleywickham</a>&#39;s 2014 <a href="https://twitter.com/user2014_ucla?ref_src=twsrc%5Etfw">@user2014_ucla</a> tutorial on Dplyr to motivate myself to keep pushing through ... learning new tools is hard for everyone at the beginning! <a href="https://t.co/RevpkSJqWc">pic.twitter.com/RevpkSJqWc</a></p>&mdash; Aliakbar Akbaritabar (Ali) (@Akbaritabar) <a href="https://twitter.com/Akbaritabar/status/1022057084802748416?ref_src=twsrc%5Etfw">July 25, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>^[[Hadley Wickham](http://hadley.nz/) is the R guru amongst gurus. He developed `dplyr`, `ggplot2`, (and many other R packages) and now is Chief Scientist for RStudio, leading the direction of RStudio's research. If you want some idea of his contribution, see [his GitHub repos](https://github.com/hadley?tab=repositories).]

# Slides & Lab

1. Introduction to Visual Analytics: [full screen](../../slides/01-class.html#1) / [pdf version](https://github.com/wesslen/dsba5122-fall2019/raw/master/public/files/dsba5122-fall2019-01-class.pdf)

```{r echo=FALSE}
knitr::include_url('../../slides/01-class.html#1')
```

[Click here and press F for full screen](../../slides/01-class.html#1).

2. Michael Friendly's Psych 6135: Psychology of Data Visualization  [Introduction and Overview](http://euclid.psych.yorku.ca/www/psy6135/lectures/Overview.pdf)

3. Lab: Intro to R/RStudio and RMarkdown

- Create a RStudio.Cloud account [rstudio.cloud](http://rstudio.cloud/).

- Go to [healy-dataviz](https://rstudio.cloud/spaces/22733/project/160035) in our class RStudio Workplace.

Our first exercise will be running [Chapter 2: Get started](http://socviz.co/gettingstarted.html) in Healy (02_get_started.Rmd).

The great thing with RStudio.Cloud, is that I already installed all of the packages. 

However, if you want to run this on your own local machine, you'll need to install all of the packages locally. To get started, you'll need to follow [Kieran's instructions](https://kieranhealy.org/blog/archives/2018/12/12/teaching-and-learning-materials-for-data-visualization/) to get the `socviz` package.

