---
title: "Visual Representation Basics II"
date: "2019-02-04"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

# Slides

[Download the slides from today's lecture]().

- Jenny Bryan's [ggplot2 tutorial GitHub](https://github.com/jennybc/ggplot2-tutorial) / [slides](https://speakerdeck.com/jennybc/ggplot2-tutorial)

- Allison Hill's [Data Visualization in the Tidyverse
The Great Tidy Plot Off](https://alison.netlify.com/uo-tidy-bakeoff/)

- [Make your own animated plots with `gganimate`](https://gganimate.com/)

# Lab 3: Make a plot (ggplot2)

- Go to our [healy-dataviz](https://rstudio.cloud/spaces/7976/project/160035) project and open "04_show_the_right_numbers.Rmd".

- This covers [Chapter 4: Show the right numbers](http://socviz.co/groupfacettx.html#groupfacettx) in Kieran Healy, *Data Visualization* [@Healy:2018]. If we have time, we'll also try to cover some parts of [Chapter 5: Group tables, add labels, make notes](http://socviz.co/workgeoms.html#workgeoms), which is the file "05_tables_and_labels.Rmd".

# Tweet of the Day

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">🌟 guide to visual encoding types from <a href="https://twitter.com/tamaramunzner?ref_src=twsrc%5Etfw">@tamaramunzner</a>&#39;s &quot;Visualization &amp; Journalism&quot; <a href="https://t.co/A2x96QYNoL">https://t.co/A2x96QYNoL</a> <a href="https://twitter.com/hashtag/dataviz?src=hash&amp;ref_src=twsrc%5Etfw">#dataviz</a> <a href="https://twitter.com/hashtag/infovis?src=hash&amp;ref_src=twsrc%5Etfw">#infovis</a> <a href="https://t.co/2FIyXeWk4h">pic.twitter.com/2FIyXeWk4h</a></p>&mdash; Mara Averick (@dataandme) <a href="https://twitter.com/dataandme/status/1052631850273918977?ref_src=twsrc%5Etfw">October 17, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>^[[Tamara Munzner](https://www.cs.ubc.ca/~tmm/) is one of the most influential data visualization researchers. Her textbook ["Visualization Analysis and Design"](https://www.amazon.com/Visualization-Analysis-Design-AK-Peters-dp-1466508914/dp/1466508914/ref=mt_hardcover?_encoding=UTF8&me=&qid=) is one of the most popular data viz books and some of her students are now leaders in data viz (e.g., [Matt Brehmer](https://mattbrehmer.github.io/), [Melanie Tory](https://www.melanietory.com/), [Michael Seldmair](https://homepage.univie.ac.at/michael.sedlmair/), and [Miriah Meyer](https://www.cs.utah.edu/~miriah/)).] ,^[[Mara Averick](https://twitter.com/dataandme) is RStudio's `tidyverse` developer advocate, which essentially means she's one of the most influential champions of all things `tidyverse`. She is an absolute [must-follow on Twitter](https://twitter.com/edwin_thoen/status/901740217987719170) and noted "data sciolist" who excels at commmunicating the technical issues of `tidyverse` in a non-technical way, e.g., [her 2018 RStudio::conf talk](https://www.rstudio.com/resources/videos/phrasing-communicating-data-science-through-tweets-gifs-and-classic-misdirection/). ]
