---
title: "Time & Space"
date: "2019-09-16"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

# Announcements

1. [Problem Set 1](../../assignment/01-problem-set.html) is due tonight by 11:59pm Monday, Sept 16th. 50% penalty if turned in within 24 hours of deadline. 0% credit if turned in 24+ hours of deadline.

2. [Quiz 1](../../assignment/01-quiz.html) has closed. We will review answers in class.

3. [DataCamp 2](../../assignment/02-datacamp.html) is due by 11:59pm Tuesday, Sept 24th. Same policies as DataCamp 1.

4. Modifications in schedule, e.g., corrected the schedule for Fall Break. [Problem Set 2](../../assignment/02-problem-set.html) has been assigned but the deadline was pushed back one week (now due Monday, Oct 7). However, be aware of upcoming assignments relative to Fall Break .

# Tweet of the day

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">👌 Dead-simple 3D surface plotting in the next version of rayshader! Apply your hillshade (or any image) to a 3D surface map. Video preview with rayshader&#39;s built-in palettes. <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a><br><br>Code:<br><br>elmat %&gt;%<br> sphere_shade() %&gt;% <br> add_shadow(ray_shade(elmat)) %&gt;% <br> plot_3d(elmat) <a href="https://t.co/FCKQ9OSKpj">pic.twitter.com/FCKQ9OSKpj</a></p>&mdash; Tyler Morgan-Wall (@tylermorganwall) <a href="https://twitter.com/tylermorganwall/status/1013760588307095552?ref_src=twsrc%5Etfw">July 2, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
^[For more details, see the [`rayshader`](https://www.rayshader.com/) package website. There are other great posts by Tyler like [doing 3D `ggplot` charts](https://www.tylermw.com/3d-ggplots-with-rayshader/) and [3D maps with `rayshader`](https://www.tylermw.com/3d-maps-with-rayshader/).  Please note - like anything cutting edge -  this package may have bugs and dependencies that require you to set up the right tools. So only pursue if you're up for the challenge.]

# Lab 4: Ch. 5 and Ch. 7 of Healy

1. Go to our [healy-dataviz](https://rstudio.cloud/spaces/22733/project/160035) project.

2. We'll start with Healy [Chapter 5: Graph tables, add labels, make notes](http://socviz.co/workgeoms.html): Open file `05_tables_and_labels.Rmd`. We'll go through the code until line 190: "05-tables-and-labels-14".

3. In class exercise (30 min). See [Slides 2](../../slides/04-class.html#2).

4. [Chapter 8: Draw Maps](http://socviz.co/maps.html#maps) in Healy. Open file `07_maps.Rmd`.

# Slides

[full screen](../../slides/04-class.html#1) / [pdf version](https://github.com/wesslen/dsba5122-fall2019/raw/master/public/files/dsba5122-fall2019-04-class.pdf)

```{r echo=FALSE}
knitr::include_url('../../slides/04-class.html#1')
```

# Links: For deeper dives into time/spatial data

1. [R Graph Gallery](http://r-graph-gallery.com)^[See the Evolution and Map sections for a ton of template functions, especially using `ggplot2`]

2. [Make your own animated plots with `gganimate`](https://gganimate.com/)

3. [R advanced spatial lessons by Ben Best](http://benbestphd.com/R-adv-spatial-lessons/tidy.html)

4. [Statnmap's Introduction to mapping with `sf` and company](https://statnmap.com/2018-07-14-introduction-to-mapping-with-sf-and-co/)

5. [LittleMissData's Map plots created with R and `ggmap`](https://www.littlemissdata.com/blog/maps)

