---
title: "Distributions & Uncertainty"
date: "2019-09-23"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

# Annoucements

1. [DataCamp 2](../../assignment/02-datacamp.html) is due by 11:59pm Tuesday, Sept 24th.

2. Reminder that [Problem Set 2](../../assignment/02-problem-set.html) is due by 11:59pm Monday, Oct 7th (during Fall Break).

3. Next week Quiz 3 will be assigned. Focus will be on readings since Quiz 2 and `ggplot2`.

# Tweet of the Day:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">My <a href="https://twitter.com/tapestryconf?ref_src=twsrc%5Etfw">@tapestryconf</a> talk is now in video form: A biased tour of the uncertainty visualization zoo. If you liked the version with just slides, you&#39;ll love (?) the version with me talking over slides :) <a href="https://t.co/hSdczZlgKW">https://t.co/hSdczZlgKW</a></p>&mdash; Matthew Kay (@mjskay) <a href="https://twitter.com/mjskay/status/1071139021231964162?ref_src=twsrc%5Etfw">December 7, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>^[Matthew Kay is an assistant professor of Information at the University of Michigan School of Information. His research focuses on communicating uncertainty, especially from a Bayesian perspective including authoring the [`tidybayes` package](https://mjskay.github.io/tidybayes/). If you're new to Bayesian statistics, he has an [excellent paper](http://www.mjskay.com/papers/chi_2016_bayes.pdf) on why Bayesian statistics is appropriate for human-centered (HCI) research. I also highly recommend [his research appearance on the DataStories podcast](http://datastori.es/134-visualizing-uncertainty-with-jessica-hullman-and-matthew-kay/) with his colleague, Jessica Hullman.]

# Slides:

[full screen](../../slides/05-class.html#1) / [pdf version](https://github.com/wesslen/dsba5122-fall2019/raw/master/public/files/dsba5122-fall2019-05-class.pdf)

```{r echo=FALSE}
knitr::include_url('../../slides/05-class.html#1')
```

# Lab 5:

For the lab session, we'll use the same [`gganimate` project](https://rstudio.cloud/spaces/7976/project/211237) from last week that's on our RStudio.cloud workspace.

If we have time, I also included Matthew Kay's [Uncertainty visualization examples](https://github.com/mjskay/uncertainty-examples) in the RStudio.cloud project (see uncertainty-examples folder).^[Be sure to check out Claus Wilke's [`ungeviz`](https://wilkelab.org/ungeviz/index.html) package.]

# Links:

Kristoffer Magnusson's visualization demos:

* [Bayesian Inference: An Interactive Visualization](http://rpsychologist.com/d3/bayes/)

* [Interpreting Confidence Intervals](http://rpsychologist.com/d3/CI/)

[Multiple Views Blog: They Draw it (eliciting users' prior beliefs)](https://medium.com/multiple-views-visualization-research-explained/theydrawit-an-authoring-tool-for-belief-driven-visualization-b3267a001480) \ [Try out TheyDrawit](https://theydrawit.mucollective.co)

StackOverflow: [Difference between Bayesian and Boostrapping](https://stats.stackexchange.com/questions/25286/when-to-use-bootstrap-vs-bayesian-technique)^[Or if you want even more technical, see the [Wikipedia page on Expected Loss](https://en.wikipedia.org/wiki/Loss_function#Expected_loss). This gets at the core difference between Bayesian and Frequentist schools of thought.]

Pierre Dragicevic's ["Fair statistical communication in HCI"](../../readings/dragicevic-fair-reporting.pdf) paper.^[This paper is an excellent guide for ways to appropriately communicate statistical models and uncertainty. This provides a good background on why overemphasis on p-values and dichotomous testing can go wrong and miss important perspectives when doing hypothesis testing.]
