---
title: "Networks & Trees"
date: "2019-10-14"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

# Announcements

1. Quiz 2

2. [Problem Set 2](../../assignment/02-problem-set/)

3. [Design Contest](../../assignment/design-contest/) next week and [DataCamp 3](../../assignment/03-datacamp/) due in two weeks (Nov 5.)

# Tweet of the day

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">New <a href="https://twitter.com/hashtag/shiny?src=hash&amp;ref_src=twsrc%5Etfw">#shiny</a> app! Something I&#39;ve been playing around with for a while - a <a href="https://twitter.com/hashtag/dataviz?src=hash&amp;ref_src=twsrc%5Etfw">#dataviz</a> of actors appearing in Wes Anderson films. Now interactive! Using the <a href="https://twitter.com/hashtag/wesanderson?src=hash&amp;ref_src=twsrc%5Etfw">#wesanderson</a> 🎨📦 of course! Along with <a href="https://twitter.com/hashtag/tidygraph?src=hash&amp;ref_src=twsrc%5Etfw">#tidygraph</a> and <a href="https://twitter.com/hashtag/visNetwork?src=hash&amp;ref_src=twsrc%5Etfw">#visNetwork</a>.<a href="https://t.co/vQz3IiNnNP">https://t.co/vQz3IiNnNP</a><a href="https://twitter.com/hashtag/SoDS19?src=hash&amp;ref_src=twsrc%5Etfw">#SoDS19</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/QcNqsqNiVP">pic.twitter.com/QcNqsqNiVP</a></p>&mdash; David Smale 🔎 (@committedtotape) <a href="https://twitter.com/committedtotape/status/1146499893831327747?ref_src=twsrc%5Etfw">July 3, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

# Slides:

[full screen](../../slides/08-class.html#1) / [pdf version](https://github.com/wesslen/dsba5122-fall2019/raw/master/public/files/dsba5122-fall2019-08-class.pdf)

```{r echo=FALSE}
knitr::include_url('../../slides/08-class.html#1')
```

# Links:

- Spring 2019 DSBA5122 Group 4's Final Project by Bala Kuppusamy, Minglan Ye, Jiamin Lei: [Social Butterfly Shiny App](https://balavigneswaran-kuppusamy.shinyapps.io/network/) and [Project GitHub repo](https://github.com/bala-kuppusamy/visual-design) ^[That team combined their Design Contest and Final Project on one GitHub repo.]

- Network Centrality measures by David Schoch's ["Introduction to Centrality Measures"](http://blog.schochastics.net/post/network-centrality-in-r-introduction/) blog post and [`netrankr` package](https://schochastics.github.io/netrankr/). ^[While there are only a handful of centrality measures that are typically used, there are many different ones that capture slightly different relationships. See David's [periodic table of centrality measures](http://schochastics.net/sna/periodic.html) for a more holistic outline of these measures.]

- François Briatte's [`ggnet` package](https://briatte.github.io/ggnet/)^[François has a really cool set of pages that show legislature co-sponorship for 27 countries, for example the [US Congress](https://f.briatte.org/parlviz/congress/plots.html) or [interactive plots for many European legislatures](https://f.briatte.org/parlviz/riksdag/).]

# Lab: Networks & Trees

- RStudio Cloud project for [sample Shiny apps](https://rstudio.cloud/spaces/22733/project/630868)
