---
title: "Intro to Shiny"
date: "2019-11-04"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

# Tweet of the day

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">New blog post: &quot;Advice to aspiring data scientists: start a blog&quot; <a href="https://t.co/yMDHqviiBN">https://t.co/yMDHqviiBN</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://t.co/9AdPUdbjtE">pic.twitter.com/9AdPUdbjtE</a></p>&mdash; David Robinson (@drob) <a href="https://twitter.com/drob/status/930492543187513345?ref_src=twsrc%5Etfw">November 14, 2017</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

^[David authored ["Tidy Text Mining"](https://www.tidytextmining.com/), which you'll use in problem set 3. David also occasionally does #tidytuesday [live coding sessions](https://twitter.com/drob/status/1190295915082452992?s=20). Extremely helpful to watch him in action.]

# Announcements

1. Design Contest Feedback

2. [Final Project](../../content/assignment/final-project.html)

3. [Problem Set 3](../../content/assignment/03-problem-set.html) is due in two weeks.

4. Quiz 3 delayed a week. Will be assigned next week and due . If possible, I will try this week to post the required readings in advance (but it's almost all of the required readings/lectures). 

5. [DataCamp 3](../../content/assignment/03-datacamp.html) due tomorrow by midnight

# Slides:

[full screen](../../slides/10-class.html#1) / [pdf version](https://github.com/wesslen/dsba5122-spring2019/raw/master/public/files/dsba5122-spring2019-10-class.pdf)

```{r echo=FALSE}
knitr::include_url('../../slides/10-class.html#1')
```

# Lab: Sample Shiny Apps

- RStudio Cloud project for [sample Shiny apps](https://rstudio.cloud/spaces/22733/project/454724)
