---
title: "Reactive Programming"
date: "2019-11-11"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

# Announcements

* [Problem Set 3](../../assignment/03-problem-set/) due next by 11:59pm next Monday (11/18)

* [Quiz 3](../../assignment/03-quiz/) has been assigned and will be available at midnight. It is due next before class 5:59pm next Monday (11/18).

* [DataCamp 4](../../assignment/04-datacamp/) due date has been pushed back to Tuesday (11/26).

* You should have your groups and your dataset for your [Final Project](../../assignment/final-project/). 

# Tweet(s) of the day:

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Excited to announce my next book project: mastering shiny, <a href="https://t.co/0mhQs57TDp">https://t.co/0mhQs57TDp</a>. I didn’t write shiny, but I’m having fun writing about it! <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a></p>&mdash; Hadley Wickham (@hadleywickham) <a href="https://twitter.com/hadleywickham/status/1161404141396250624?ref_src=twsrc%5Etfw">August 13, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

# Hands-on Class

* Garrett Grohlmund's [Introduction to Reactivity in Shiny](../../files/shiny-reactivity.pdf) ^[If you need more understanding on Reactivity, be sure to read this [Reactivity Overview by RStudio](https://shiny.rstudio.com/articles/reactivity-overview.html)]
  
* In-Class Practice: Questions 1-5 in Wickham ["Mastering Shiny" Chapter 2.8 Exercises](https://mastering-shiny.org/basic-app.html)^[I will send out an RStudio.Cloud project with the correct answers after class.]

* Also recall our RStudio Cloud project with [150+ sample Shiny apps](https://rstudio.cloud/spaces/22733/project/454724). 
