---
title: "Interactions & Frameworks"
date: "2019-11-18"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

# Announcements

- Quiz 3 grades.

- [Problem Set 4](../../assignment/04-problem-set/) posted. We'll spend the last half of class starting this.

- [DataCamp 4](../../assignment/04-datacamp/) due 11:59pm on Tuesday, Nov 26. 

# Tweet(s) of the day:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">🎅 Major announcement for <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> shiny addicts🎅:<br>Excited to officially introduce RinteRface, a collection of open-source HTML templates for <a href="https://twitter.com/hashtag/shiny?src=hash&amp;ref_src=twsrc%5Etfw">#shiny</a> and more 🦄<br>Thanks <a href="https://twitter.com/jdatap?ref_src=twsrc%5Etfw">@jdatap</a> for joining the project 🔥<a href="https://t.co/IAX76FEz1k">https://t.co/IAX76FEz1k</a><a href="https://twitter.com/ZurichRUsers?ref_src=twsrc%5Etfw">@ZurichRUsers</a> <a href="https://twitter.com/dataandme?ref_src=twsrc%5Etfw">@dataandme</a> <a href="https://twitter.com/minebocek?ref_src=twsrc%5Etfw">@minebocek</a> <a href="https://twitter.com/_pvictorr?ref_src=twsrc%5Etfw">@_pvictorr</a> <a href="https://t.co/WCvuAxJiI4">pic.twitter.com/WCvuAxJiI4</a></p>&mdash; David Granjon (@divadnojnarg) <a href="https://twitter.com/divadnojnarg/status/1067804524495192064?ref_src=twsrc%5Etfw">November 28, 2018</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

^[[RinteRface](https://rinterface.com/) includes several web frameworks as R packages including: [`shinydashboardPlus`](https://github.com/RinteRface/shinydashboardPlus),  [`bs4Dash`](https://github.com/RinteRface/bs4Dash),  [`argonDash`](https://rinterface.github.io/argonDash/).]

# Hands-on Class

## Creating PowerPoint using R

Tarun Sharma will show a quick demo on using `officer` package to create PowerPoints using R. [RStudio Cloud project](https://rstudio.cloud/project/701622)

## Hands-on Work

We'll heavily use our RStudio Cloud project for [sample Shiny apps](https://rstudio.cloud/spaces/22733/project/454724). 

* Review app 93 (basic interactions)^[93-107 apps are interactive Shiny Apps] , app 114 (Modal Dialog/Pop Ups) and others.

Next, we'll use this [RStudio.Cloud project](https://rstudio.cloud/spaces/22733/project/707339) to introduce interaction (`/interactions/` folder), `shinydashboard` and related `shinywidgets` (`/shinydashboard/` folder), last other helpful shiny widgets (`/widgets/` folder).

The last hour of class will be time for you to work with your groups or begin Problem Set 4.

# Helpful Links

## 1. Brusing & interaction:

- JJ Alaire's [`flexdashboard` shiny-enabled brushing](https://jjallaire.shinyapps.io/shiny-ggplot2-brushing/), John Coene's [`echarts4r`](https://echarts4r.john-coene.com/articles/shiny.html),  [`crosstalk`](https://rstudio.github.io/crosstalk/using.html),^[`echarts4r` interactivity is based on `crosstalk`, e.g., see [this brushing/slider tutorial](https://echarts4r.john-coene.com/articles/brush.html).] or [`plotly`](https://plotly-r.com/linking-views-with-shiny.html) ^[Specifically see Chapter 15-17 of Carson Sievert's book.]

## 2. [`shinydashboard`](https://rstudio.github.io/shinydashboard/)

- [Omayma Said's Intro to Shiny Workshop](https://github.com/OmaymaS/intro_to_shiny_workshop/)

## 3. Helper functions: [`dragulaR`](https://github.com/zzawadz/dragulaR),  [`shinyWidgets`](https://github.com/dreamRs/shinyWidgets) / [shiny demo](http://shinyapps.dreamrs.fr/shinyWidgets/), and [`waiter`](https://shiny.john-coene.com/waiter/)

## 4. Optional slides

- <i class="fas fa-book"></i> [Week 10: Interactions](https://github.com/wesslen/dsba5122-fall2019/raw/master/static/readings/10-Interaction.pdf) and [Week 11: Views](https://github.com/wesslen/dsba5122-fall2019/raw/master/static/readings/11-Views.pdf) by Alexander Lex, *CS-5630 / CS-6630 Visualization for Data Science*
