---
title: "Python"
date: "2019-12-02"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

# Announcements

## Final Projects. Due next class 12/9. 

Your final project will have three deliverables due on [Canvas](https://uncc.instructure.com/courses/110218/assignments/681957):

* Your app (e.g., as a zip file, github, RStudio.Cloud link)

* Your presentation slides (e.g., pptx or zip file with `xaringan`)^[If you submit xaringan, I highly recommend submitting a .pdf that you can get by viewing your `xaringan` in full screen, then right click > "print" and then save as pdf.]

* Your final report (e.g., word doc, pdf, html RMarkdown output)

All are due by 6:00pm next Monday (12/9). Please make sure to submit well in advance. 

For any of the three projects, you may also provide URL's but files are the safest bets. You will **not** be permitted to make any updates after that point. 

## Course Evaluations

Due by 11:59pm on Thursday, December 5. 

Can be completed here: <https://myevals.uncc.edu>

# Tweet of the day

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Just released Altair version 3.0! This is a huge update, with many new visualization features and bug-fixes thanks to the hard work of the <a href="https://twitter.com/vega_vis?ref_src=twsrc%5Etfw">@vega_vis</a> team.<br><br>Check it out: <a href="https://t.co/PCyrIOTcvv">https://t.co/PCyrIOTcvv</a> <a href="https://t.co/0YT2ckQizl">pic.twitter.com/0YT2ckQizl</a></p>&mdash; Jake VanderPlas (@jakevdp) <a href="https://twitter.com/jakevdp/status/1121824167790137345?ref_src=twsrc%5Etfw">April 26, 2019</a></blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> ^[Altair is based on Vega and Vega-Lite, another creation by Jeff Heer and his lab. You can try [Vega and Vega-lite here](https://vega.github.io/editor/#/custom/vega-lite)! There is also a [vegalite](https://github.com/hrbrmstr/vegalite) R package.]

# Slides/Lab

[full screen](../../slides/14-class.html#1) / [pdf version](https://github.com/wesslen/dsba5122-fall2019/raw/master/public/files/dsba5122-fall2019-14-class.pdf)

```{r echo=FALSE}
knitr::include_url('../../slides/14-class.html#1')
```
