---
title: "Quiz 2"
date: "2019-10-14"
due_date: "2019-10-21"
due_time: "5:59 PM"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

Quiz 2 can be taken starting on October 15th: [Canvas link to Quiz 2](https://uncc.instructure.com/courses/110218/quizzes/140149)

1. You will have one week to complete the quiz (that is, the quiz must be completed by 5:59pm on October 21, 2019). Note this is not by midnight, but before the next class.

2. This quiz will consist of 10 multiple choice questions. You will have *20 minutes* to complete the quiz. You may only take the quiz once. Grades will not be available until the quiz closes.

3. You will be required to use in-browser locking to prevent you from having other materials open.

4. Per the syllabus, you are **not allowed to use any resources** (slides, notes, other people, etc.) when taking this quiz. By taking the quiz, you pledge **on your honor** that you did not use any unauthorized resource.

5. **No late quizzes accepted**. If you do not complete the quiz in time, you will receive 0% grade.

# Scope

1. Time/Spatial (Week 4): [Wilke Chapters 13-15](https://serialmentor.com/dataviz/time-series.html) (1-3 questions)

2. Distributions/Uncertainty (Week 5): [Wilke Chapters 7-9](https://serialmentor.com/dataviz/histograms-density-plots.html) (same as Slides 6-19) and [Wilke Chapter 16](https://serialmentor.com/dataviz/visualizing-uncertainty.html) (similar to Slides 22-25) (1-3 questions)

3. Models (Week 6): [Healy Chapter 6](http://socviz.co/modeling.html) (1-3 questions)

4. DataCamp 2: Exploratory Data Analysis in R: Case Study (5+ questions). For practice, your best resource is the associated DataCamp practice questions: <https://practice.datacamp.com/p/19>. 

