---
title: "Quiz 3"
date: "2019-11-11"
due_date: "2019-11-18"
due_time: "5:59 PM"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

Quiz 3 can be taken starting on November 12th: [Canvas link to Quiz 3](https://uncc.instructure.com/courses/110218/quizzes/140168)

1. You will have one week to complete the quiz (that is, the quiz must be completed by 5:59pm on November 18, 2019).^[This is not by midnight, but **before the next class**.]

2. This quiz will consist of 10 multiple choice questions. You will have *15 minutes* to complete the quiz. You may only take the quiz once. Grades will not be available until the quiz closes.^[I moved this quiz back to 15 minutes.]

3. You will be required to use in-browser locking to prevent you from having other materials open.

4. Per the syllabus, you are **not allowed to use any resources** (slides, notes, other people, etc.) when taking this quiz. By taking the quiz, you pledge **on your honor** that you did not use any unauthorized resource.

5. **No late quizzes accepted**. If you do not complete the quiz in time, you will receive 0% grade.

# Scope

## 1. Multidimensional (Week 7): 2-4 questions

- [Week 7 Lecture Slides](../../slides/07-class.html#1)

- <i class="fas fa-book"></i> [Chapter 12: Visualizing associations](https://serialmentor.com/dataviz/visualizing-associations.html) in Claus Wilke, *Fundamentals of Data Visualization* 

- <i class="fas fa-book"></i> [Chapter 4: Multivariate Analysis](../../readings/Mazza2009_Chapter_MultivariateAnalysis.pdf) in Riccardo Mazza, *Introduction to Information Visualization* 

## 2. Networks and Trees (Week 8): 2-4 questions

- [Week 8 Lecture Slides](../../slides/08-class.html#1)

- <i class="fas fa-book"></i> [Chapter 5: Networks and Hierarchies](../../readings/Mazza2009_Chapter_NetworksAndHierarchies.pdf) in Riccardo Mazza, *Introduction to Information Visualization*

## 3. Intro to Shiny (Week 10): (2-4 questions)

- [Week 10 Lecture Slides](../../slides/10-class.html#1)

- <i class="fas fa-book"></i> [Chapters 2: Your First Shiny App](https://mastering-shiny.org/basic-app.html), [Chapters 3: Basic UI](https://mastering-shiny.org/basic-ui.html), and [Chapters 4: Basic Reactivity](https://mastering-shiny.org/basic-reactivity.html) in Hadley Wickham *Mastering Shiny* 
