---
title: "Quiz 4"
date: "2019-11-25"
due_date: "2019-12-02"
due_time: "11:59 PM"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

Quiz 4 can be taken starting on November 25: [Canvas link to Quiz 4](https://uncc.instructure.com/courses/110218/quizzes/140169)

1. You will have one week to complete the quiz (that is, the quiz must be completed by 5:59pm on December 2nd, 2019).^[This is not by midnight, but **before the next class**.]

2. This quiz will consist of 10 multiple choice questions. You will have *15 minutes* to complete the quiz. You may only take the quiz once. Grades will not be available until the quiz closes.

3. You will be required to use in-browser locking to prevent you from having other materials open.

4. Per the syllabus, you are **not allowed to use any resources** (slides, notes, other people, etc.) when taking this quiz. By taking the quiz, you pledge **on your honor** that you did not use any unauthorized resource.

5. **No late quizzes accepted**. If you do not complete the quiz in time, you will receive 0% grade.

# Scope

## 1. Reactivity (Week 11): (2-4 questions)

- [Week 11 Lecture Slides](https://dsba5122.com/files/shiny-reactivity.pdf)

## 2. Interactivity (Week 12): (2-4 questions)

- Study the `/interactions/` folder examples from <https://rstudio.cloud/spaces/22733/project/707339>

## 3. DataCamp 4: (2-4 questions)

- [Building Web Applications in R with Shiny: Case Studies](../../assignment/04-datacamp/)


